---
- name: Backup running-config
  cisco.ios.ios_command:
    commands: show running-config
  register: backup_config_output

- name: Save running config locally
  ansible.builtin.copy:
    content: "{{ backup_config_output.stdout[0] }}"
    dest: "./backups/{{ inventory_hostname }}_running_config.txt"