---
- name: Network Automation in doing ETL using AWS Glue
  hosts: all
  gather_facts: false
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
  tasks:
    - name: Create local directories for outputs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "./logs"
        - "./backups"
        - "./interfaces"

    - name: Collect logs from the network device
      ansible.builtin.include_role:
        name: collect_logs

    - name: Get the backup of the configuration
      ansible.builtin.include_role:
        name: backup_config

    - name: Get the interface stats
      ansible.builtin.include_role:
        name: interface_stats

    - name: Render the interface config report
      ansible.builtin.include_role:
        name: render_interface_report
